fps: 24
map: Town10HD                                                           # Available towns ['Town01', 'Town01_Opt', 'Town02', 'Town02_Opt', 'Town03', 'Town03_Opt', 'Town04', 'Town04_Opt', 'Town05', 'Town05_Opt', 'Town10HD', 'Town10HD_Opt'] 
no_of_vehicles: 30
synchronous: True

out_dir: "F:\\CARLA_0.9.16\\PythonAPI\\carla_data_tools\\cfg\\data"
capture_frequency: 20
sensor_preview: True
capture_data: True
