fps: 10
map: Town01_Opt                                                           # Available towns ['Town01', 'Town01_Opt', 'Town02', 'Town02_Opt', 'Town03', 'Town03_Opt', 'Town04', 'Town04_Opt', 'Town05', 'Town05_Opt', 'Town10HD', 'Town10HD_Opt'] 
no_of_vehicles: 30
synchronous: True

out_dir: "D:\\WindowsNoEditor\\PythonAPI\\carla_data_tools\\data"
capture_frequency: 1
sensor_preview: True
capture_data: True
