vehicle: 'tesla.model3'

sensors: [
            {sensor_type: RGBCamera,
             sensor_name: image_2,
             image_size_x: 1382,
             image_size_y: 512,
             fov: 110,
             translation: [0.27, 0.06, 1.65],
             rotation: [0, 0, 0],
             depth: True,
             sem_seg: True
             }
]