vehicle: 'tesla.model3'

sensors: [
            {sensor_type: RGBCamera,
             sensor_name: image_2,
             image_size_x: 1382,
             image_size_y: 512,
             fov: 110,
             translation: [0.27, 0.06, 1.65],
             rotation: [0, 0, 0],
             depth: True,
             sem_seg: True
             },

             {sensor_type: LiDAR,
             sensor_name: velodyne,
             channels: 64,
             points_per_second: 1_300_000,
             rotation_frequency: 10,
             noise_stddev: 0.2,
             upper_fov: 2.0,
             lower_fov: -24.8,
             range: 120,
             sensor_tick: 0.0,
             dropoff_general_rate: 0.1,
             dropoff_intensity_limit: 0.8,
             dropoff_zero_intensity: 0.4,
             vehicle_detection_threshold: 20,
             translation: [0,0,1.73],
             rotation: [0, -180, 0]}
]